/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 cube.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/cube.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0, 1.476, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.wave} scale={0.695} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[0, 1.056, 0]} scale={0.59} />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[-0.001, 2.602, 0]} scale={0.181} />
        <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} position={[-0.001, 2.602, 0]} scale={0.181} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[0, 1.056, 0]} scale={0.59} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.003']} position={[0, 0.008, -1.8]} scale={[84.519, 8.452, 8.452]} />
        <mesh name="linear_Gradient_PSD" geometry={nodes.linear_Gradient_PSD.geometry} material={materials['Material.001']} position={[-4.286, 6.489, 5.75]} rotation={[Math.PI, -0.575, Math.PI / 2]} scale={7.782} />
        <mesh name="linear_Gradient_PSD001" geometry={nodes.linear_Gradient_PSD001.geometry} material={materials['Material.002']} position={[8.069, 6.489, -0.385]} rotation={[Math.PI, -0.419, Math.PI / 2]} scale={[7.782, 7.782, 6.046]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cube.gltf')
