/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Final.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Final.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Cube.geometry} 
        material={materials['Material.001']} 
        scale={0.695}
        castShadow={true}
        receiveShadow={true} >
      </mesh>
    </group>
  )
}

useGLTF.preload('/Final.gltf')
